# Generated by Django 3.1 on 2020-09-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('coffee_photo', models.ImageField(blank=True, default='profile_pics/log.jpg', upload_to='foods')),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dessert_photo', models.ImageField(blank=True, default='profile_pics/log.jpg', upload_to='foods')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(blank=True, max_length=100, null=True)),
                ('drink_photo', models.ImageField(blank=True, default='profile_pics/log.jpg', upload_to='foods')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, max_length=100, null=True)),
                ('food_photo', models.ImageField(blank=True, default='profile_pics/log.jpg', upload_to='foods')),
            ],
        ),
    ]
