# Generated by Django 3.1 on 2020-09-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dessert_photo', models.ImageField(blank=True, default='profile_pics/log.jpg', upload_to='foods')),
            ],
        ),
    ]
